# Danh sách URL vendor chính thống để nạp làm nguồn trích dẫn
urls:
  - https://expressjs.com/en/guide/routing.html
  - https://expressjs.com/en/guide/writing-middleware.html
  - https://expressjs.com/en/guide/using-middleware.html
  - https://expressjs.com/en/guide/overriding-express-api.html
  - https://expressjs.com/en/guide/using-template-engines.html
  - https://expressjs.com/en/guide/error-handling.html
  - https://expressjs.com/en/guide/debugging.html
  - https://expressjs.com/en/guide/behind-proxies.html
  - https://expressjs.com/en/guide/advanced-routing.html
  - https://expressjs.com/en/guide/faq.html
